.gitignore, build.gradle, settings.gradle, step-json/build.gradle, step-json/src/main/xml/ancillary.xml, step-json/src/main/xml/conformance.xml, step-json/src/main/xml/specification.xml, step-json/src/main/xml/steps/join-json.xml
Just a skeleton that @xml-project asked me to add.
=> Add a JSON step specification

step-text/src/main/xml/steps/markdown-to-html.xml
The text on this step had some copy-and-paste problems. Additionally I shortened the lines a bit.
=> Fixed text

steps/src/main/xml/steps/xslt.xml
Try to fix the signature of p:xslt. Does this work?
=> Fix signature of p:xslt

steps/src/main/xml/steps/directory-list.xml
=> Attempt to fix 58

steps/src/main/xml/steps/xslt.xml
=> Clarify XSLT error codes

steps/src/main/xml/steps/make-absolute-uris.xml
=> Attempt to fix 73

steps/src/main/xml/steps/add-xml-base.xml
=> Attempt to fix issue 71

steps/src/main/xml/steps/escape-markup.xml
Fix #77 by removing the notion of a document element.
=> Attempt to fix 77

steps/src/main/xml/steps/filter.xml
=> Attempt to fix 79

steps/src/main/xml/steps/escape-markup.xml
=> Attempt to fix 75

steps/src/main/xml/steps/pack.xml
=> Attempt to fix 84

steps/src/main/xml/steps/namespace-rename.xml
=> Attempt to fix 86 and 90

step-json/src/main/xml/steps/join-json.xml
Third try: Now it is just one commit, so I hope, everyone sees the same as me.
=> p:json-join

steps/src/main/xml/steps/directory-list.xml
That is, https://github.com/xproc/3.0-steps/issues/89#issuecomment-493342536 (except max-depth, which still needs to be discussed)
=> address issues discussed in #89

src/main/schema/core30.rnc, steps/src/main/xml/steps/directory-list.xml
hopefully reflect the consensus recorded in https://github.com/xproc/3.0-steps/issues/89#issuecomment-500468624
=> Directory list

steps/src/main/xml/steps/add-attribute.xml, steps/src/main/xml/steps/delete.xml, steps/src/main/xml/steps/hash.xml, steps/src/main/xml/steps/insert.xml, steps/src/main/xml/steps/rename.xml, steps/src/main/xml/steps/set-attributes.xml, steps/src/main/xml/steps/string-replace.xml, steps/src/main/xml/steps/uuid.xml, steps/src/main/xml/steps/wrap.xml, steps/src/main/xml/steps/www-form-urlencode.xml
Addresses https://github.com/xproc/3.0-specification/issues/810 for the steps. Changes the words "match pattern" into "selection pattern"
=> Changed words match pattern to selection pattern (as a glossterm)

steps/src/main/xml/steps/cast-content-type.xml, steps/src/main/xml/steps/text-join.xml
=> Attempt to fix 102

steps/src/main/xml/steps/insert.xml
Attempt to fix #103 
- @position is no longer required
- @position's default value is 'after'
=> Attempt to fix 103

steps/src/main/xml/steps/archive.xml, steps/src/main/xml/steps/unarchive.xml
Changes related to #116.
I almost completely rewrote the `p:archive` section (without hopefully breaking any intended meaning) because in my opinion it was not clear and not strict enough. So @gimsieke, please read it carefully.
I think it will be rather problematic to verify all changes without seeing the resulting HTML (and I didn't yet master the art of creating GitHub pages for my forked repos). We could merge the PR and take it from there. 
There is still one editorial note that I have no answer for. To be discussed in a call I think.
=> 116 archive steps

steps/src/main/xml/steps/replace.xml
=> Attempt to fix 93

steps/src/main/xml/steps/hash.xml, steps/src/main/xml/steps/string-replace.xml
=> Attempt to fix 100

steps/src/main/xml/steps/unwrap.xml
=> Attempt to fix 129

steps/src/main/xml/steps/delete.xml
=> Attempt to fix 122

steps/src/main/xml/steps/uuid.xml
=> Attempt to fix 135

steps/src/main/xml/specification.xml, steps/src/main/xml/steps/archive-manifest.xml
=> Added p:archive-manifest

steps/src/main/xml/steps/escape-markup.xml
=> Attempt to fix 144

step-validation/src/main/xml/specification.xml, steps/src/main/xml/specification.xml, steps/src/main/xml/steps/archive-manifest.xml, steps/src/main/xml/steps/archive.xml
Might still need a little refinement, but I tried to get down the basic idea.
=> Markup errors and a fix for #138

step-os/src/main/xml/specification.xml
=> Fix for the FIXME in p:os-info

steps/src/main/xml/steps/store.xml
Trying to fix 106 for p:store. Did I get everything?
=> Attempt to fix 106 for p:store

steps/src/main/xml/steps/www-form-urldecode.xml, steps/src/main/xml/steps/www-form-urlencode.xml
I am not sure I got all aspects of this issue, so please read carefully and tell me, what I missed or what you want me to change.
=> First attempt on issue 22

.travis.yml, build.gradle, gradle/wrapper/gradle-wrapper.properties
This attempts to switch to OpenJDK12
=> Switch to OpenJDK

steps/src/main/xml/steps/xslt.xml
Now we can catch specific errors in try/catch, we should be able to tell them apart.
=> Adding new more fine grained error for p:xslt

step-paged-media/src/main/xml/specification.xml
Also remove statement about `@href`.
Fix #163
=> Editorial change to the XSL formatter step spec

step-validation/src/main/xml/specification.xml
=> Make port schema sequence

step-json/src/main/xml/steps/join-json.xml, step-os/src/main/xml/specification.xml, step-text/src/main/xml/steps/markdown-to-html.xml, steps/src/main/xml/steps/archive-manifest.xml, steps/src/main/xml/steps/archive.xml, steps/src/main/xml/steps/namespace-rename.xml, steps/src/main/xml/steps/set-properties.xml, steps/src/main/xml/steps/text-join.xml, steps/src/main/xml/steps/text-replace.xml, steps/src/main/xml/steps/text-sort.xml, steps/src/main/xml/steps/unarchive.xml
=> Cleanup optional option types

steps/src/main/xml/steps/hash.xml, steps/src/main/xml/steps/replace.xml, steps/src/main/xml/steps/string-replace.xml, steps/src/main/xml/steps/unwrap.xml, steps/src/main/xml/steps/uuid.xml
Attempt to fix #130 
For p:unwrap I just removed the error case for matching the document node.
=> Attempt to fix step issue 130

steps/src/main/xml/steps/xslt.xml
Fixed wrong error codes according to wiki error list.
=> Fixed error codes in p:xslt

steps/src/main/xml/steps/xslt.xml
=> Attempt to fix 186 and 187

step-validation/src/main/xml/specification.xml, steps/src/main/xml/steps/xquery.xml, steps/src/main/xml/steps/xslt.xml
=> Attempt to fix 182

steps/src/main/xml/steps/archive.xml
Just fixing a misspelled error code.
=> Fixed an error code in p:archive

steps/src/main/xml/steps/archive.xml
=> Attempt to fix-207

steps/src/main/xml/steps/xslt.xml
=> Changed text of error messages as requested

steps/src/main/xml/steps/json-join.xml
=> Attempt to fix 181

steps/src/main/xml/steps/xslt.xml
=> Attempt to fix #215

steps/src/main/xml/specification.xml, steps/src/main/xml/steps/uncompress.xml
=> Attempt to resolve issue #114/uncompress

steps/src/main/xml/steps/xslt.xml
=> Attempt to fix-222

steps/src/main/xml/steps/set-properties.xml
Attempt to fix #220 
- Option merge is now true by default
- Little change of prose to improve clarity.
=> Attempt to fix 220

steps/src/main/xml/steps/xquery.xml
=> Attempt to fix 226

steps/src/main/xml/specification.xml, steps/src/main/xml/steps/namespace-delete.xml
Attempt to fix #87 New step "p:namespace-delete" modelled after cx:namespace-delete.
=> Attempt to fix 87

steps/src/main/xml/steps/set-properties.xml
Attempt to fix 880 (main specs). Please mind there is a corresponding pr there.
=> Attempt to fix 880 (main specs)

steps/src/main/xml/steps/json-join.xml
Reworked p:json-join in line to p:json-merge: Taking all kinds of docs on source, creating an arrays.
=> Attempt to fix 233

steps/src/main/xml/steps/uncompress.xml
=> Removal of XC0200 - As by #229

src/main/resources/css/xproc.css, tools/xsl/dbspec.xsl, tools/xsl/docbook.xsl
I pulled a few things out of the most recent W3C CSS. The font's a little bigger, the lines are a little further apart, and there's a max-width of 50em.
=> Update the CSS

steps/src/main/xml/steps/archive.xml
Attempt to fix #244 and fixing a typo in err:C0100.
=> Attempt to fix 244

steps/src/main/xml/steps/load.xml, steps/src/main/xml/steps/set-properties.xml
Changes in the core specs are now reflected in p:load and p:set-properties.
=> Step changes to fix 889

steps/src/main/xml/steps/load.xml, steps/src/main/xml/steps/set-properties.xml
Reverts xproc/3.0-steps#250 
Please see: https://github.com/xproc/3.0-specification/issues/894
and https://github.com/xproc/3.0-specification/pull/895
=> Revert "Step changes to fix 889"

step-file/src/main/xml/specification.xml
Editorial update on the file steps. #253
=> Attempt to resolve 253

build.gradle
This turns diffs back on;if diffs were working...
=> Added specid back in

steps/src/main/xml/steps/unarchive.xml
Attempt to fix #268 @gimsieke please mind the hyphens ;-))
=> Attempt to fix 268

steps/src/main/xml/steps/archive-manifest.xml, steps/src/main/xml/steps/archive.xml, steps/src/main/xml/steps/load.xml, steps/src/main/xml/steps/unarchive.xml
Changed error text of XD0064 as suggested by @gimsieke [https://github.com/xproc/3.0-specification/issues/916].
=> Fixed error text

step-file/src/main/xml/specification.xml
=> Attempt to fix 274

steps/src/main/xml/steps/archive-manifest.xml, steps/src/main/xml/steps/archive.xml, steps/src/main/xml/steps/compress.xml, steps/src/main/xml/steps/unarchive.xml
Close #283 
Close #286 
Close two other bugs I didn't get around top opening 😄
=> Fix Q*n*ame typos

steps/src/main/xml/steps/json-join.xml
Fix #291 by introducing a new error (C0119).
=> Attempt to fix 291

steps/src/main/xml/steps/text-sort.xml
#297 seems almost to easy... :)
=> Resolve issue 297 - Changed collation  name

steps/src/main/xml/steps/archive-manifest.xml, steps/src/main/xml/steps/archive.xml, steps/src/main/xml/steps/unarchive.xml
=> Attempt to fix 300

steps/src/main/xml/steps/archive-manifest.xml, steps/src/main/xml/steps/unarchive.xml
=> Attempt to fix 298

steps/src/main/xml/steps/archive.xml
=> Clarify processing of ZIP archives

steps/src/main/xml/steps/text-count.xml, steps/src/main/xml/steps/text-head.xml, steps/src/main/xml/steps/text-join.xml, steps/src/main/xml/steps/text-replace.xml, steps/src/main/xml/steps/text-sort.xml, steps/src/main/xml/steps/text-tail.xml
=> Attempt to resolve text end-of-line handling questions

step-file/src/main/xml/specification.xml, step-os/src/main/xml/specification.xml, step-paged-media/src/main/xml/specification.xml, step-rdf/src/main/xml/specification.xml, step-run/src/main/xml/specification.xml, step-text/src/main/xml/specification.xml, step-validation/src/main/xml/specification.xml, steps/src/main/xml/specification.xml
=> Happy New Year

src/main/xml/bibliography.xml, step-paged-media/src/main/xml/specification.xml
=> Describe p:css-formatter

src/main/xml/bibliography.xml, steps/src/main/xml/references.xml, steps/src/main/xml/specification.xml
=> Fix FIXME:s

steps/src/main/xml/steps/load.xml
=> Add an error code for failing to load HTML

steps/src/main/xml/steps/wrap-sequence.xml, steps/src/main/xml/steps/wrap.xml
=> Clarify equality of group adjacent values

steps/src/main/xml/steps/archive-manifest.xml
Don't think this is controversial.
=> Fixed a typo

steps/src/main/xml/steps/make-absolute-uris.xml
=> Attempt to fix 270

steps/src/main/xml/steps/xslt.xml
Fix #271
Created a new error code for this case as XD0064 is for options
=> Attempt to fix-271

steps/src/main/xml/steps/text-join.xml
=> Attempt to fix 319

step-file/src/main/xml/specification.xml
=> p:file-touch: create file if it doesn’t exist

step-file/src/main/xml/specification.xml, step-os/src/main/xml/specification.xml, steps/src/main/xml/steps/www-form-urldecode.xml, steps/src/main/xml/steps/www-form-urlencode.xml
=> document properties of steps without primary inputs

steps/src/main/xml/steps/http-request.xml
=> Fixed typo

tools/travis-publish-spec.sh
Publish the grammar files and step libraries to the grammar repo.
=> Fix Travis publication

steps/src/main/xml/specification.xml, steps/src/main/xml/steps/xslt.xml
=> Added static-parameters option to p:xslt

steps/src/main/xml/specification.xml, steps/src/main/xml/steps/archive-manifest.xml, steps/src/main/xml/steps/unarchive.xml
Issue #364 
Added error for invalid regular expressions. Will apply this error to other steps where applicable as of #378
=> Specification for override content type

step-file/src/main/xml/specification.xml
Attempt to solve #351 and #352 
Let's see, if we can create another controversy ;-))
=> Attempt to solve #351 and #352

step-file/src/main/xml/specification.xml
=> Added override-content-types option to p:directory-list and p:file-info

steps/src/main/xml/specification.xml, steps/src/main/xml/steps/archive-manifest.xml, steps/src/main/xml/steps/cast-content-type.xml, steps/src/main/xml/steps/http-request.xml, steps/src/main/xml/steps/text-join.xml, steps/src/main/xml/steps/uncompress.xml
=> Attempt to fix 382

steps/src/main/xml/steps/archive-manifest.xml, steps/src/main/xml/steps/unarchive.xml
=> Clarification of paths in acrchives

build.gradle, gradle.properties, steps/src/main/xml/steps/archive-manifest.xml, tools/xsl/dbspec.xsl
1. Fixed a markup error in archive-manifest.
2. Support xspecref from step-file to steps.
=> Fix xspecref

step-validation/src/main/xml/specification.xml, steps/src/main/xml/specification.xml, steps/src/main/xml/steps/store.xml
This PR, along with corresponding changes in the specification repo is an attempt to close specification issue 968
=> Attempt to resolve spec issue 968

steps/src/main/xml/steps/archive.xml
Will add the entry to the change log as soon as this gets approved. Not sure whether it would interfere with other PRs if I do it now.
=> Attempt to fix issue 401

steps/src/main/xml/steps/xslt.xml
=> Attempt to fix 410

steps/src/main/xml/specification.xml, steps/src/main/xml/steps/xslt.xml
Attempt to fix #400 as agreed in the last editors call.
=> Attempt to fix issue 400

step-os/src/main/xml/specification.xml
This is a first draft of my ideas on how to make p:os-exec more XProc 3.0 like.
Will add the entry to the change log as soon as this gets approved. Not sure whether it would interfere with other PRs if I do it now.
=> First draft to fix 403

steps/src/main/xml/specification.xml, steps/src/main/xml/steps/http-request.xml
Attempt to fix #409 
Does this work?
=> Attempt to fix issue 409

steps/src/main/xml/specification.xml, steps/src/main/xml/steps/load.xml
I hope I have hit all those plurals.
=> Attempt to fix 418

step-validation/src/main/xml/specification.xml
=> Attempt to fix 397

step-validation/src/main/xml/specification.xml
Attempt to close #425 Introducing different error codes for different validation steps.
=> Attempt to fix 425

steps/src/main/xml/references.xml
Close #396 
Maybe we should add references for some of these, but in the short term, this removes the FIXME comments.
=> Remove unreferenced bibligraphy entries

steps/src/main/xml/steps/http-request.xml
I sure this reflects our consensus, but I am not sure this is good and understandable English.
Any suggestion welcomed.
=> Attempt to fix 398

src/main/resources/css/db-prism.css, tools/xsl/docbook.xsl
This is a parallel change to the specification repo.
=> Update tools to produce syntax-highlighted listings without line numbers

step-file/src/main/xml/specification.xml
Could somebody please have a look at these changes. If we agree what we want to have for p:file-copy, I will apply this to p:file-move respectively.
=> Attempt to fix 433 for p:file-copy

steps/src/main/xml/steps/xquery.xml
"string value" is wrong here, should read "serialization"
=> Attempt to fix problem in p:xquery

step-file/src/main/xml/specification.xml
Attempt to close #433 
I agree that the semantics @ndw spelled out in https://github.com/xproc/3.0-steps/issues/433#issuecomment-659504931 is right. The existing prose reflects his proposal, so the only thing I needed to do was to add an error for the uncovered case.
=> Small fix for p:file-move

step-paged-media/src/main/xml/specification.xml
=> Attempt to fix 441

step-validation/src/main/xml/specification.xml
=> Attempt to fix 453

build.gradle, steps/src/main/xml/specification.xml, tools/xpl/formatspec.xpl, tools/xsl/docbook.xsl
Fixed a few infrastructure issues.
=> Last call draft

steps/src/main/xml/steps/archive.xml
Issue #462: Text changes/clarifications for the handling of the `relative-to` option
=> Some small text changes for issue 462

step-run/src/main/xml/specification.xml
Address #468, #466, #465, #450, #449
=> Further clarifications wrt p:run

.circleci/publish.sh
Update the Circle CI configuration to publish steps and grammar changes to the specification and grammar repositories.
=> Circle CI publication

step-file/src/main/xml/specification.xml
=> Attempt to clarify some aspects of p:file-copy

.gitignore, build.gradle, settings.gradle, src/main/xml/bibliography.xml, step-ixml/build.gradle, step-ixml/src/main/examples/ambig-1.xml, step-ixml/src/main/examples/ambig-2.xml, step-ixml/src/main/examples/ambig-3.xml, step-ixml/src/main/examples/dates-1.xml, step-ixml/src/main/examples/dates-2.xml, step-ixml/src/main/examples/dates-3.xml, step-ixml/src/main/xml/ancillary.xml, step-ixml/src/main/xml/conformance.xml, step-ixml/src/main/xml/specification.xml
This is my first cut at a standard `p:ixml` step on the hopefully not unwarranted belief that we want one.
=> First draft of an ixml step

steps/src/main/xml/steps/www-form-urlencode.xml
I do not think this should be controversial.
=> Attempt to fix #491

steps/src/main/xml/steps/insert.xml, steps/src/main/xml/steps/json-merge.xml, steps/src/main/xml/steps/namespace-rename.xml
=> Attempt to fix #490

steps/src/main/xml/steps/http-request.xml
Attempt to fix #486 Error condition removed as proposed by @ndw
=> Attempt to fix 486

step-file/src/main/xml/specification.xml
=> Attempt to fix 504

step-file/src/main/xml/specification.xml
=> Attempt to fix 505

step-file/src/main/xml/specification.xml
=> Attempt to fix 506

step-file/src/main/xml/specification.xml
=> Attempt to fix 510

step-validation/src/main/xml/specification.xml
=> Attempt to fix 512

src/main/xml/bibliography.xml, step-validation/src/main/xml/specification.xml
This proposal includes step errors XC0163, XC0164 and XC0165. These error code **have not been** registered in the error wikki yet.
=> A proposal for a JSON validation step

steps/src/main/xml/steps/xslt.xml
It seems silly not to fix such a small editorial issue. Thank you, @xml-project 
Close #515
=> Fix the editorial error in p:xslt wrt populate-default-collection

step-os/src/main/xml/specification.xml
=> Attempt to fix 520

step-file/src/main/xml/specification.xml
Added <rfc2119>must</rfc2119> for additional namespaced attributes.
=> Added rfc2119

step-run/src/main/xml/specification.xml
=> Attempt to fix 534

step-run/src/main/xml/specification.xml
Fix #526 by explicitly requiring a version attribute on pipeline root in p:run
=> Attempt to fix 526

src/main/xml/bibliography.xml, step-validation/src/main/xml/specification.xml
- Added p:validate-with-json-schema to the step list in the introducing.
- Fixed broken link to XVRL spec
=> Editorial fixes:

step-os/src/main/xml/specification.xml
=> Attempt to fix 540

step-ixml/src/main/examples/ambig-1.xml, step-ixml/src/main/examples/ambig-2.xml, step-ixml/src/main/examples/ambig-3.xml, step-ixml/src/main/examples/dates-1.xml, step-ixml/src/main/examples/dates-2.xml, step-ixml/src/main/examples/dates-3.xml
Fixed the examples in p:ixml spec
=> Fixed examples

.github/workflows/build-pr.yml, .github/workflows/build-specs.yml, build.gradle, buildSrc/src/main/groovy/com/nwalsh/tasks/StripAmblesTask.groovy, gradle/wrapper/gradle-wrapper.properties, settings.gradle, step-file/build.gradle, step-mail/build.gradle, step-os/build.gradle, step-paged-media/build.gradle, step-rdf/build.gradle, step-text/build.gradle, step-validation/build.gradle, steps/build.gradle
Parallel to the [recent change](https://github.com/xproc/3.0-specification/pull/1087) on the specifications repo.
=> Infrastructure upgrades

steps/src/main/xml/steps/rename.xml
=> Clarify err:XC0023

steps/src/main/xml/steps/add-attribute.xml, steps/src/main/xml/steps/set-attributes.xml
I think reusing `err:XC0059` on `p:set-attributes` is the right thing to do...
=> Clarify err:XC0059, add it to p:set-attributes

step-run/src/main/xml/specification.xml
Renaming C0201 -> C0206 and C0202->C0207
=> Attempt to fix 567

step-file/src/main/xml/specification.xml
=> Improve the description of include-file processing in p:directory-list

steps/src/main/xml/steps/hash.xml, steps/src/main/xml/steps/replace.xml, steps/src/main/xml/steps/string-replace.xml, steps/src/main/xml/steps/uuid.xml
This makes the improvement we agreed to in #570
=> Make the agreed improvement to #566

steps/src/main/xml/steps/compare.xml
=> Make the result port primary on p:compare

step-file/src/main/xml/specification.xml
=> Make access to special files implementation defined

steps/src/main/xml/steps/archive.xml
=> Remove err:XC0118 in favor of err:XC0100

steps/src/main/xml/specification.xml, steps/src/main/xml/steps/sleep.xml
=> Add p:sleep step

src/main/resources/css/xproc.css
More, hopefully uncontroversial, tweaks. I bumped the font size by 10% and added a little syntax highlighting to the declaration summaries.
=> CSS tweaks

src/main/resources/css/xproc.css
=> Harmonize CSS across specification/steps

step-file/src/main/xml/conformance.xml, step-file/src/main/xml/specification.xml
Are they ready for publication?
=> Editorial pass on file steps

step-os/src/main/xml/specification.xml
Are they ready for publication?
=> Editorial pass on OS steps

step-paged-media/src/main/xml/conformance.xml, step-paged-media/src/main/xml/specification.xml
=> Editorial pass on paged media steps

step-mail/src/main/xml/specification.xml, step-text/src/main/xml/specification.xml, step-validation/src/main/xml/specification.xml, steps/src/main/xml/steps/http-request.xml, steps/src/main/xml/steps/json-join.xml, steps/src/main/xml/steps/json-merge.xml, steps/src/main/xml/steps/sleep.xml, steps/src/main/xml/steps/uncompress.xml, steps/src/main/xml/steps/xquery.xml, steps/src/main/xml/steps/xslt.xml, tools/xsl/dbspec.xsl, tools/xsl/xprocns2.xsl
=> Fix markup error

step-validation/src/main/xml/specification.xml
=> Editorial improvements and clarifications to p:validate-with-dtd

steps/src/main/xml/steps/archive.xml
Fixes https://github.com/xproc/3.0-specification/issues/1112
=> Describe the comment attribute on c:entry elements

steps/src/main/xml/steps/load.xml
=> Clarify access errors in p:load

build.gradle, src/main/resources/js/scroll.js, step-file/src/main/xml/specification.xml, step-ixml/src/main/xml/specification.xml, step-mail/src/main/xml/specification.xml, step-os/src/main/xml/specification.xml, step-paged-media/src/main/xml/specification.xml, step-run/src/main/xml/specification.xml, step-text/src/main/xml/specification.xml, step-validation/src/main/xml/specification.xml, steps/src/main/xml/specification.xml
Updated the copyright year, changed the status, updated the change log.
=> Editorial updates for second last call draft
