src/main/xml/bibliography.xml, steps/src/main/xml/references.xml, steps/src/main/xml/specification.xml, steps/src/main/xml/steps/archive.xml, steps/src/main/xml/steps/unarchive.xml
I created skeleton entries for the p:archive and the p:unarchive steps. I suggest we use these as a starting point for further refinements (even if they're not complete yet), unless I of course totally interpreted things wrong. And even then, something to start with and bicker about is better than nothing.
This is for #3 en #4, based on my interpretation of the minutes of Prague, https://github.com/xproc/Workshop-2019-02/wiki/Meeting-minutes-Wednesday
The specifications need a schema extension for their manifest file(s) but that is currently beyond my abilities.
=> Skeleton archive unarchive steps

steps/src/main/xml/steps/archive.xml, tools/xsl/library-to-rnc.xsl
Steps that have options of type xs:string* and xs:uri* will no longer cause RELAX NG errors.
I fixed a couple of markup errors in the p:archive step.
=> Fix string star

steps/src/main/xml/steps/hash.xml
Trying to fix #78 
I changed to signature (source = xml html / result = xml html) and added an error for a replacement like "/" resulting in a single text node. 
We might allow this but then it is a new (text) document and we can no longer say, that all document properties are preserved (for the content-type changed!)
=> Attempt to fix 78

src/main/schema/core30.rnc, steps/src/main/xml/steps/archive.xml
Also provide an RNC schema for the manifest.
I renamed Erik’s `c:file` back to to `pxp:zip`’s `c:entry` so that we don’t have to differentiate between `c:file` in directory listings and `c:file` in archive entries.
=> attempt to improve p:archive (archive input port, manifestless creation, …)

src/main/schema/core30.rnc, steps/src/main/xml/steps/directory-list.xml
Not sure whether the change in src/main/schema/core30.rnc will immediately show in the generated syntax boxes. We might need to update the same file in the 3.0-specification repo.
=> remove uri attribute on c:directory; correct xml:base in example

steps/src/main/xml/steps/unescape-markup.xml
Attempt to fix #137 
(a) More than one top-level element is an error.
(b) document properties are preserved.
=> Attempt to fix 137

steps/src/main/xml/steps/set-attributes.xml
Attempt to fix #94 
Port "attributes" removed and using map as option instead.
=> Attempt to fix 94

steps/src/main/xml/steps/archive.xml
Update of `p:archive` to reflect the decisions of last call. See #116.
Two things to notice:
* The `c:entry/@href` attribute must become mandatory but I don't know how to do that. See #150
* I kept kept the default `zip` value for the `format` option. I really don't see how a `p:archive` should know what kind of format to create if you don't tell it.
=> Updated p:archive to refelect decisions made in last call

steps/src/main/xml/steps/unarchive.xml
This implements #116 for the decisions we made in our last call about `p:unarchive` 
I made a decision about the base URI of unarchived documents which we did not discuss, might be controversial, please comment: 
>The base URI of an unarchived document appearing on the result port is the relative path of this document as it was in the archive. For instance, the base URI of an unarchived file called xyz.xml that resided in the specs subdirectory in the archive will become specs/xyz.xml.
=> Updated p:unarchive to decisions made in last call

steps/src/main/xml/references.xml, steps/src/main/xml/steps/xquery.xml
This is a second attempt to resolve #104 
@xml-project was right in his comment about the previous PR: There was mainly some superfluous outdated text there about the XQuery output that I could just delete. So the main change is a paragraph delete.
I checked with the description of p:xslt but this also says nothing about the output of the step. And rightfully so: That is described in the core spec.
=> Fixing p:xquery description

steps/src/main/xml/steps/xslt.xml
Just added a catchable error code to mark that an XSLT stylesheet is not statically valid.
=> Adding error to p:xslt

steps/src/main/xml/steps/xslt.xml
I rewrote p:xslt to fix the problems in #61 and #159 . 
I introduces three subsections, so invocation of XSLT 1.0, 2.0 and 3.0 is now treated separately. As the terminology from 2.0 to 3.0 changed dramatically, this approach makes it easier to use the relevant terminology without interfering with the others.
Proposal: If you do not think it is completely non-sense, I would suggest to approve this PR and then file issue, so we do lot loss track of the necessary changed.
=> Rewriting p:xslt for issues 61 and 159

steps/src/main/xml/errors.xml
Issue number 113 in the test-suite is actually caused by the fact that the steps specification does not list the dynamic errors (err:XD...) in the errors appendix.
This PR fixes that.
=> Add dynamic errors to the errors appendix

step-validation/src/main/xml/specification.xml
Attempt to fix #183 : As application/relax-ng-compact-syntax now is a text media type, we do not have to call it out here.
=> Attempt to fix 183

steps/src/main/xml/steps/archive-manifest.xml, steps/src/main/xml/steps/archive.xml, steps/src/main/xml/steps/unarchive.xml
I do not think this is controversial:
- Replaced "\*/*" on ports with "any"
- Harmonized sequence type of archive ports: It was "application/\*" on p:archive, but "\*/*" on the two other steps. Now it is "any" on all.
=> Fix archive steps

steps/src/main/xml/steps/archive.xml
I think the same mechanism should be used and the same type of errors should be raised in both cases.
=> Added archive type detection mechanism as set out in p:archive-manifest

steps/src/main/xml/steps/text-sort.xml
Attempt to fix #197 
- I used "sort-key" because it feels more natural to me then "select". The only "select" in the step library I found is on p:filter and there it really select a portion of a document. If I am the only one arguing against "select" I am perfectly prepared to give in.
- My proposal keeps option `data-type` but removes the default value, so there a two ways to enforce a special sort mechanism:
````
<p:sort sort-key="xs:integer(substring(., 1, 5))" />
````
or
````
<p:sort sort-key="substring(., 1, 5)" data-type="numeric" />
````
As far as I can see, data-type on xsl:sort is only for legacy reason, so if you opt to remove `data-type`, I am perfectly happy with this.
=> Attempt to fix 197

steps/src/main/xml/steps/xslt.xml
This was obvious from the prose, but the `impl` element was missing. Fixed this to make sure, it goes to the list of implementation defined features.
=> Just added note that supported xslt versions are implementation defined.

steps/src/main/xml/steps/xquery.xml
=> Attempt to fix 205

steps/src/main/xml/steps/store.xml
Attempt to fix #217 : If "file:" is supported, non existing folders should be created.
=> Attempt to fix issue 217

steps/src/main/xml/steps/compress.xml, steps/src/main/xml/steps/uncompress.xml
Added an additional error message for when `p:compress` and `p:uncompress` do not understand or cannot determine the compression format.
=> Additional error condition for #114

steps/src/main/xml/specification.xml, steps/src/main/xml/steps/json-merge.xml
Attempt to fix #180 
New step p:json-merge. As @ndw observed, this can't be done with XPath because it depends on the order of documents on port `source`. (Remember collection() does not preserve order.)
=> Attempt to fix 180

steps/src/main/xml/steps/json-merge.xml
Introduced a new error if evaluation of `key` is not an atomic value or a node.
=> New error when evaluating key

steps/src/main/xml/steps/namespace-delete.xml
This is a (hopefully) totally uncontroversial PR: There was an error in the id of the namespace-delete step (it was called c.sink and this must be c.namespace-delete).
My book pipelines failed over this so therefore I noticed.
=> Id fix on namespace delete

build.gradle, gradle.properties, tools/xpl/formatspec.xpl, tools/xsl/docbook.xsl, tools/xsl/xprocns.xsl
1. Bump the versions of XML Calabash and the DocBook stylesheets
2. Support `p:empty` as a default input in step declarations.
=> Infrastructure upgrades

build.gradle, settings.gradle, step-rdf/build.gradle, step-rdf/build/glossary.xml, step-rdf/build/library.xml, step-rdf/build/source.xml, step-rdf/build/steps.rnc, step-rdf/build/steps.rng, step-rdf/build/xinclude.xml, step-rdf/src/main/xml/ancillary.xml, step-rdf/src/main/xml/conformance.xml, step-rdf/src/main/xml/specification.xml
This PR adds a placeholder spec for RDF steps.
=> Added rdf steps

steps/src/main/xml/references.xml, steps/src/main/xml/steps/archive-manifest.xml, steps/src/main/xml/steps/archive.xml, steps/src/main/xml/steps/unarchive.xml
This turned out to be quite a change due to our decisions that base URIs must be absolute. I had to change `p:archive`, `p:archive-manifest` and `p:unarchive`.
All three now have a `relative-to` option that can be used to set the base URI for the files *in* the archive.
I also made the choice to have all relevant URIs to be normalized first by `p:urify()`. This applies to values passed to the `relative-to` option and the values of the manifest's `c:entry/@href` attributes. IMHO this is in line with the decisions we made about this for setting base URIs on our last call.
=> Attempt to resolve issue 251

steps/src/main/xml/steps/set-properties.xml
Stating in p:set-properties, that base-uri changed base URI and XD0064 is raised on an error.
=> Changes set-properties as consequence of 889

steps/src/main/xml/steps/cast-content-type.xml
This is a first sketch for the revised "p:cast-content-type" (see #16). I tried to include @ndw's proposal to parse and serialize e.g. xml->text and vice versa. Also I try to come up for document property "serialization" which was not covered yet.
I do not expect an approve yet, but propose to discuss this on next editors call.
=> First sketch on p:cast-content-type

steps/src/main/xml/steps/cast-content-type.xml
I fixed a few build warnings. The gloss terms used an emdash instead of a hypen in "implementation-defined"; this prevented the cross references from being found.
It turns out that all sections need to have `xml:id`s. The error if you put an `impl` in a section that doesn't have one was very odd!
=> Fix simple typos in cast-content-type

steps/src/main/xml/steps/archive.xml, tools/xsl/dbspec.xsl
Is set out to fix #296 
Along the way, I attempted to improve the prose in a few other places.
P.S. The question of hierarchical schemes is resolved in RFC 3986. All URIs have paths.
=> Clarify how a manifest entry is constructed

src/main/xml/bibliography.xml, step-text/src/main/xml/specification.xml, step-text/src/main/xml/steps/markdown-to-html.xml
Fix #39 
I think this counts as a fix. We've moved the other text steps into the core step library, so this one can be for the markdown step. We might find more text-like steps to add later
=> Clean up the specification of p:markdown-to-html

steps/src/main/xml/steps/archive-manifest.xml, steps/src/main/xml/steps/archive.xml, steps/src/main/xml/steps/compare.xml, steps/src/main/xml/steps/count.xml, steps/src/main/xml/steps/error.xml, steps/src/main/xml/steps/filter.xml, steps/src/main/xml/steps/http-request.xml, steps/src/main/xml/steps/insert.xml, steps/src/main/xml/steps/json-join.xml, steps/src/main/xml/steps/json-merge.xml, steps/src/main/xml/steps/load.xml, steps/src/main/xml/steps/pack.xml, steps/src/main/xml/steps/text-count.xml, steps/src/main/xml/steps/text-join.xml, steps/src/main/xml/steps/text-tail.xml, steps/src/main/xml/steps/unarchive.xml, steps/src/main/xml/steps/unwrap.xml, steps/src/main/xml/steps/wrap-sequence.xml, steps/src/main/xml/steps/wrap.xml, steps/src/main/xml/steps/www-form-urldecode.xml, steps/src/main/xml/steps/www-form-urlencode.xml, steps/src/main/xml/steps/xquery.xml, steps/src/main/xml/steps/xslt.xml, tools/xsl/dbspec.xsl
On reflection, I decided that it would be better to clarify the base URI of standard steps. Here's what I changed:
1. I made it explicit that `p:archive`, `p:archive-manifest`, `p:compare`, `p:count`, `p:error`, `p:json-join`, `p:json-merge`, `p:pack`, `p:text-count`, `p:text-join`, `p:wrap-sequence`, `p:www-form-urldecode`, and `p:www-form-urlencode` produce documents with no base URI.
2. I made it explicit that the base URI(s) of the document(s) produced by `p:filter`, `p:unarchive`, `p:http-request`, `p:load`, `p:xquery`, `p:xslt` reflect the base URIs that one would expect.
3. I changed `p:wrap`, `p:unwrap` to say that they preserve *all* properties instead of none. I think none was a catagorization error that we never noticed.
4. I clarified the situation for `p:insert` a little bit.
=> Clarify the base-uri property of standard steps

step-os/src/main/xml/specification.xml, step-paged-media/src/main/xml/specification.xml, step-rdf/src/main/xml/specification.xml, step-run/src/main/xml/specification.xml, step-validation/src/main/xml/specification.xml, steps/src/main/xml/steps/archive.xml, steps/src/main/xml/steps/cast-content-type.xml, steps/src/main/xml/steps/compare.xml, steps/src/main/xml/steps/count.xml, steps/src/main/xml/steps/http-request.xml, steps/src/main/xml/steps/text-join.xml
=> Fix step content-types (use shortcuts)

steps/src/main/xml/steps/http-request.xml
Please find here the first draft on p:http-request which is to replace the existing text comming from the 1.0 specs.
@ndw @xatapult @Gertone @gimsieke 
"Edit from maintainers" is on, so feel free to make changes.
=> First draft of p:http-request

step-file/src/main/xml/specification.xml
The schema already reflects that `c:file` may have a `content-type` attribute. Now it’s also in the prose.
=> add the missing prose for #128

steps/src/main/xml/steps/http-request.xml
close #332 
I fixed the prose. IMHO we should have a short intro to cover the two simple cases: No document or one document. Multipart request should then be covered last in the same named section.
=> Attempt to fix 332

steps/src/main/xml/steps/http-request.xml
Fixed different spelling of key "auth-method" or "method" in map "auth".
=> Fixed different spellings of a key in auth

src/main/xml/bibliography.xml, steps/src/main/xml/references.xml, steps/src/main/xml/steps/http-request.xml
Right. Here's my attempt to complete the `p:http-request` step. I made an editorial pass, hopefully my edits are acceptable. I made a few non-editorial change as well:
1. I removed the reference to certificates. I don't know how to write that section and I don't think we have to. We say that implementations may support additional auth-methods. Certificates can be one of them and we can come back to standardize later if we need to.
2. I renamed "multipart" to "accept-multipart"
3. I added "multipart-boundary"
4. I added "multipart-content-type"
5. I renamed the "content-encoding" parameter to "override-content-encoding" as I think it's parallel with "override-content-type".
6. I changed the "timeout" from decimal to integer because that seemed more consistent.
7. I attempt to write the …
=> Attempt to complete p:http-request

steps/src/main/xml/steps/http-request.xml
1. Fix #335 by adding an error
2. Fix #347 by clarifying headers and parameters per discussion on that issue.
3. Settle on lowercase.
=> Fix #347 by reworking headers and parameters

steps/src/main/xml/specification.xml, steps/src/main/xml/steps/http-request.xml
Attempt to fix #369
I invented a new namespace; I wonder if using the step namespace would be better.
=> Use document properties as headers only if they're in the correct namespace

build.gradle, gradle.properties, steps/src/main/xml/specification.xml
This PR gets the grammar files from github.com/xproc/3.0-grammar
(It also removes the errant 'last-call' note from the spec, since I happened to notice it.)
I don't expect either of these changes to be controversial, so I'm just going to merge them after the build passes. Unfortunately, travis-ci is down now (21 March, 10:30 UTC) so it may be a while.
=> Fix grammar

step-file/src/main/xml/specification.xml
Just added a reference for the `override-content-types` options in the file steps to where it is explained in the core steps library.
=> Clarified override-content-types option 

step-run/src/main/examples/run.xml, step-run/src/main/xml/specification.xml
@ndw I referenced `<e:rng-pattern name="Run"/>` in specification.xml. The pattern probably needs to be defined by that name in core30.rnc in the grammar repo. Maybe you can change that after you merged https://github.com/xproc/3.0-grammar/pull/17
=> proposal for p:run, #331

step-run/src/main/xml/specification.xml
The pattern in the grammar repo isn’t up to date, see https://github.com/xproc/3.0-steps/issues/421#issuecomment-648902388. I’ll try to include the current pattern nevertheless.
=> try to e:rng-pattern 'Step-run', #421

steps/src/main/xml/steps/xslt.xml
As there has been a discussion whether documents on port "secondary" of p:xslt 3.0 are ordered, I added the "unordered" note from the 2.0 section to the 3.0 section as well.
I do take this to be purely editorial, correcting an oversight. So no entry in the change log is needed.
=> Fix obscurity for secondary results of p:xslt version 3.0

step-file/src/main/xml/specification.xml
Close #353 by stating clearly that p:file-delete and p:mk-dir are idempotent
=> attempt to fix 353

step-os/src/main/xml/specification.xml
Attempt to close #415 by renaming port "errors" to "error" and option "errors-content-type" to "error-content-type"
=> Changed name of port error and option error-content-type

steps/src/main/xml/steps/xslt.xml
Just fixed a typo because prefix "err" is bound to "http://www.w3.org/ns/xproc-error" in the rest of the doc.
=> Fixed typo in p:xslt

step-mail/src/main/xml/specification.xml
I have tried to fill some gaps in this specification. If this is not complete nonsense I would suggest to merge this and have a further discussion on this base.
As the original specs had no explanation of what will appear on the `result` port I spelled out what XMLCalabash and MorganaXProc do for 1.0. Not sure that should be the last word on this topic.
A rendering is [here](https://xml-project.com/files/2020-07-21/).
=> First attempt to fill the gaps in this spec

step-mail/src/main/xml/specification.xml
From the prose it is clear that port `source` must accept _any_ content-type.
Sorry for missing this.
=> Fix content-type of port source

steps/src/main/xml/steps/error.xml
Fix for the error in the example of `p:error` #445 
Also remove the superfluous `p:inline`. The shorter the better here as far as I'm concerned.
=> Fix example in p:error

step-file/src/main/xml/specification.xml
The attribute on `p:output` is `content-types`, not `content-type`.
(I don't know what the list of `Add .circleci/config.yml` commits is about. I think they're ones I squashed away.)
=> Fix typo in directory-list

steps/src/main/xml/steps/http-request.xml
If the user specifies a boundary for a multipart request that's not valid (e.g., if it begins "--"), throw this error.
=> Added error code for invalid multipart boundary

steps/src/main/xml/steps/http-request.xml
In the course of debugging my `p:http-request` step and discussing the various test outcomes with @xml-project, the following observation was made:
If a request produces no documents, it's impossible to tell what the final URI was. In particular, consider the case where you've set `follow-redirect` to 2 but the request redirects more than twice. There's no output so there's no document from which you can get the base URI, so there's no way to know what the last redirect location was.
The simple fix seems to be to add this information to the `report` output. It seems reasonable, it's trivial to implement, and it does mean pipeline authors can rely on reading the value irrespective of whether or not a document was produced.
=> Report the base URI in the report output

tools/xsl/typed-pipeline-library.xsl
For some reason, the code that produces the `library.xpl` summary files for steps was "simplifying" any `as` attribute that contained a map or array down to `string`. I have no recollection of why.
=> Fix 'as' attributes in library.xpl

step-run/src/main/xml/specification.xml
I think this makes the step syntax tableaux consistent with the prose and the grammar. (Or rather, I made the grammar consistent with the prose so the step is now correct.)
=> Fixes for the syntax tableaux

steps/src/main/xml/specification.xml, tools/xpl/formatspec.xpl, tools/xsl/docbook.xsl
This just takes out some of the "final" markup, restores the note about the fact that it's an editorial draft, and makes diffs against the 3.0 spec instead of the last call draft.
=> Update for post-3.0 work

gradle.properties, step-validation/src/main/xml/specification.xml, steps/src/main/xml/steps/hash.xml, steps/src/main/xml/steps/replace.xml, steps/src/main/xml/steps/string-replace.xml, steps/src/main/xml/steps/uuid.xml
Fix #566 
I think I've made the prose more parallel with the discussion about attributes and less likely to confuse men of small brain like me.
I also fixed a markup error in the step-validation specification and tweaked Gradle's daemon memory, but those should be irrelevant.
=> Improve the wording about matching document nodes

steps/src/main/xml/steps/archive-manifest.xml, steps/src/main/xml/steps/archive.xml
Changed "p:archive-manifest" and "p:archive" as discussed in issue #561 and #564
=> Fix 561 and 564

steps/src/main/xml/steps/insert.xml
I don't think I can mark an issue in another repository for automatic closing. We should close 29 in the `vnext` repository when we merge this PR.
=> Allow text insertions

steps/src/main/xml/steps/text-sort.xml
=> Fix the Unicode Codepoint Collation URI

steps/src/main/xml/steps/archive.xml
Close #562 
In the end, my editorial choice was to remove the explicit declaration that they are implementation defined. They aren't for ZIP archives, so I feel justified :-)
=> Attempt to clarify p:archive parameters

step-validation/src/main/xml/specification.xml
(Assuming this will be an uncontroversial change.)
Fix #556 
Also added missing `impl` markup around the use of an implementation-defined glossterm.
=> Fix the sequence type of the default-version option

src/main/xml/bibliography.xml, steps/src/main/xml/references.xml, steps/src/main/xml/steps/text-sort.xml
Close #580 
On the one hand, I don't think this is a necessary clarification because the data type is `xs:language` and that defines (by reference) what constitutes a valid language tag. On the other hand, if it helps the reader...
=> Add a note about how xs:language codes are defined

step-paged-media/src/main/xml/specification.xml
=> Attempt to fix issue 585

steps/src/main/xml/steps/uuid.xml
This gives the user somewhere to put parameters for other forms of UUID. They remain implementation defined.
=> Fix #587 by adding a parameters option

step-validation/src/main/xml/specification.xml
This my first attempt. Feedback eagerly solicited. Formatted versions should appear on the xproc.org/dashboard page a few minutes after I create this request.
=> First cut at p:validate-with-dtd

steps/src/main/xml/specification.xml, steps/src/main/xml/steps/insert.xml
Editorial change: I replaced "The required steps" with "Step library" because we no longer have any /optional/ steps in this specification.
=> Fix #583 by allowing the result to be text

src/main/resources/css/xproc.css, tools/xsl/dbspec.xsl, tools/xsl/docbook.xsl, tools/xsl/elemsyntax.xsl, tools/xsl/library-to-rnc.xsl, tools/xsl/make-library.xsl, tools/xsl/make-rng.xsl, tools/xsl/makeglossary.xsl, tools/xsl/masterbib.xsl, tools/xsl/ml-macro.xsl, tools/xsl/pipeline-library.xsl, tools/xsl/post-pdf.xsl, tools/xsl/rngsyntax.xsl, tools/xsl/xproc-pdf.xsl, tools/xsl/xproc-specs.xsl, tools/xsl/xprocns.xsl, tools/xsl/xprocns2.xsl
I was tinkering with a step last night and got a bee in my bonnet about the style of the step summaries. My first thought was that adding some syntax highlighting would improve things. And I guess maybe it did.
Then this morning, I got distracted by the idea that maybe the whole thing could be improved and made more readable.
So here it is. It's certainly different and...I think...it's an improvement.
One observation: the links from the names of ports and options in the summary to their descriptions only work if the descriptions are formatted as a variable list. The fact that we haven't done that in a lot of places is interesting. 
This relates to @xatapult 's thoughts about refactoring the spec entirely in some future version. But in this case there's no change in the spec, just a change …
=> Restructuring the step summaries

step-run/src/main/xml/conformance.xml, step-run/src/main/xml/specification.xml
=> Editorial pass on p:run

build.gradle, settings.gradle, step-ixml/build.gradle, step-ixml/src/main/xml/specification.xml
For some reason, the build didn't include `p:ixml`. I fixed that.
I fixed #494 and #547.
I changed the content types of the `source` port given the new error changes.
=> Improvements to p:ixml

src/main/resources/css/xproc.css, steps/src/main/xml/steps/count.xml
I happened, randomly, to notice this sentence in the description of `p:count`:
> This provides a convenient mechanism to discover, for example, if a sequence consists of more than 1 document, without requiring every single document to be buffered before processing can continue.
That reference to buffering and continuing is unjustified. I've changed it to:
> This provides a convenient mechanism to discover, for example, if a sequence consists of more than 1 document, without requiring every document to be counted.
I'm not sure that's exactly true either (my implementation counts them all and then returns `min($count,$limit)`), but I think it's an improvement.
=> Small editorial change to p:count

step-validation/src/main/xml/conformance.xml, step-validation/src/main/xml/specification.xml
Ready for publication?
Note that I've clarified what the expected output of the validate-with-json-schema and validate-with-dtd steps.
I added a reference to the DTD error code 0210 which I added to the error list but failed to put in the spec!
=> Editorial pass on validation steps

steps/src/main/xml/specification.xml, steps/src/main/xml/steps/archive.xml, steps/src/main/xml/steps/compare.xml, steps/src/main/xml/steps/text-sort.xml
1. Update the publication metadata for 3.1
2. Replace the changelog with "changes since 3.0"
3. Removed the erratum sections added when we were considering doing a 3.0 with errata publication
=> Prepare for 3.1 publication

steps/src/main/xml/steps/cast-content-type.xml
1. Clarified that supporting additional XML-to-JSON conversions is implementation defined.
2. Documented `c:param-set` and `c:param`. The declarations were already in the schema, luckily.
3. I believe the prose is now prescriptive regarding the `c:param-set` and `c:param` elements.
4. I think `c:data` [is defined](https://spec.xproc.org/master/head/steps/#c.data).
Close #618 
Note that the description of `c:param` is broader here than it was in 1.0. But we made those changes in the schema long ago and I assume we did it on purpose.
=> Attempt to resolve ambiguities in p:cast-content-type

build.gradle, tools/xsl/rngsyntax.xsl, tools/xsl/typed-pipeline-library.xsl
This is a partial fix for the library version issue.
I'm not marking it to automatically close the issue because I think there are additional issues in the `3.0-grammar` repository that need to be considered.
=> Update version number in step libraries

steps/src/main/xml/steps/error.xml
I took a closer look at `p:error` and thought it could be more clearly described. Hopefully this is an improvement...
Fix #623
=> Attempt to clarify p:error

step-ixml/src/main/xml/specification.xml
Close #625 
I think this is an improvement. @gimsieke's observation about `p:xslt` notwithstanding, most of the XProc steps have names that are unabbreviated words separated by hyphens.
=> Rename p:ixml to p:invisible-xml

steps/src/main/xml/steps/filter.xml
I found a small 1.0 left-over in `p:filter` (mentioning `p:input` instead of `p:with-input`). This should fix it.
=> Fixed 1.0 left-over in p:filter

steps/src/main/xml/steps/load.xml
There was an editorial mistake in `p:load`. The first sentence repeated itself. Fixed.
=> Editorial mistake in p:load fixed

steps/src/main/xml/steps/archive.xml
The statements:
> Implementations *must* support the ZIP format, specified with the value `zip`. It is *implementation-defined* what other formats are supported.
appeared twice. In the description of compression level, the implementation defined statement about the *method* was repeated.
=> Editorial fixes for p:archive

steps/src/main/xml/steps/filter.xml
=> Allow p:filter to return non-node results

step-run/src/main/xml/specification.xml, steps/src/main/xml/steps/cast-content-type.xml, tools/xsl/rngsyntax.xsl
This is (mostly) a tooling change, but I also added a bit of markup to `p:cast-content-type` and `p:run` to make the links work.
=> Fix broken links

step-validation/src/main/xml/specification.xml
In the end, I clarified it by making it analagous to what we say for other steps.
Fix #637
=> Clarify serialization in validate-with-dtd

steps/src/main/xml/steps/text-sort.xml, steps/src/main/xml/steps/xslt.xml
This is my attempt to fix #642 
I've taken the option I described in the issue and made the global context item dependent on whether or not the value is the empty sequence, not whether or not its present. I made similar changes elsewhere to avoid the term "no value" when "empty sequence" is meant.
If we adopt this PR, the test `ab-xslt-094` will also need to be changed.
=> Avoid the term 'no value' as distinct from 'the empty sequence'

step-file/src/main/xml/specification.xml
Adapts the description of `p:file-info` output as discussed.
=> Resolving issue #648

steps/src/main/xml/steps/split-sequence.xml
Removed the superfluous PSVI request for `p:split-sequence` (issue #639)
=> Resolved issue 639: Superfluous PSVI remark removed

step-file/src/main/xml/specification.xml
This pull request fixes 3 typos in the specification for `p:directory-list`. It also rephrases a sentence that isn't wrong but that is a little awkward, in my opinion.
=> Editorial improvements in p:directory-list

steps/src/main/xml/specification.xml, steps/src/main/xml/steps/cast-content-type.xml, steps/src/main/xml/steps/encode.xml
Fix #659
In order to make the p:cast-content-type step decode any c:data document, even one that might contain serialized XML, I’ve reorganized the “Casting from an XML media type” section. The case of a c:data document is handled first.
This is a small backwards incompatibility because it means that you cannot use p:cast-content type to change the content type of a c:data element from application/xml to, for example, application/foo+xml. But that seems like something very unlikely given that we control the semantics of c:data documents. (The alternative is to create a p:decode step.)
=> Added the p:encode step

steps/src/main/xml/specification.xml, steps/src/main/xml/steps/pack.xml, steps/src/main/xml/steps/wrap-sequence.xml, steps/src/main/xml/steps/wrap.xml
Fix #656
Incidentally, changed the order of p:wrap and p:wrap-sequence so that they appear in lexicographic order in the specification.
=> Added the attributes option to p:pack, p:wrap, and p:wrap-sequence

step-os/src/main/xml/specification.xml
=> Clarify that cwd on p:os-exec is normalized with p:urify()

src/main/xml/bibliography.xml, steps/src/main/xml/references.xml, steps/src/main/xml/steps/load.xml
Fix #668 
This is a first attempt, I think it's reasonable as far as it goes, but we should look to see if there are more places where the BOM should be addressed.
=> Attempt to address the BOM

build.gradle, settings.gradle, step-message/build.gradle, step-message/build/glossary.xml, step-message/build/library.xml, step-message/build/source.xml, step-message/build/steps.rnc, step-message/build/steps.rng, step-message/build/xinclude.xml, step-message/src/main/xml/ancillary.xml, step-message/src/main/xml/specification.xml
It seems like a consensus is forming to add a `p:message` step, so I took a stab at describing it.
The only open question in my mind is, if the `test` expression is `false()`, is the implementation forbidden from evaluating the select expression or is that implementation-dependent. (Or implementation-defined, I guess.)
=> Describe a p:message step
